version: '3'

services:
  itg-ingest:
    container_name: itg-ingest
    image: projectitg/ingest
    #Uncomment below to build locally
#    image: itg-ingest
#    build:
#      context: ./ingest
#      dockerfile: Dockerfile
    env_file: '.env'
    restart: on-failure
    ports:
      - "${INGEST_PORT}:8084"

  itg-react:
    container_name: itg-react
    image: projectitg/react
    #Uncomment below to build locally
#    image: itg-react
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
    env_file: '.env'
    restart: on-failure
    ports:
      - "${WEB_PORT}:80"

  itg-webrtc:
    container_name: itg-webrtc
    image: projectitg/webrtc
    #Uncomment below to build locally
#    image: itg-webrtc
#    build:
#      context: ./webrtc
#      dockerfile: Dockerfile
    env_file: '.env'
    command: ["itg-webrtc", "--addr=0.0.0.0", "--ip=${WEBSOCKET_HOST}", "--ports=20000-20100", "--ice-servers=${ICE_SERVERS}", "run"]
    restart: on-failure
    ports:
      - ${WEBSOCKET_PORT}:8080 # WebRTC
      - 65535:65535/udp # RTP
      - 20000-20100:20000-20100/tcp # WebRTC PeerConnection
      - 20000-20100:20000-20100/udp # WebRTC PeerConnection UDP
